### ISSUE TITLE
Separate gender from name

### ISSUE THREAD

**Issue by privefl** [ThinkRstat/legislatives2017#2]
Would be nice to have the gender separated from the name, so that we can see the male-female parity (or not).

**Comment by privefl** [comment]
What we can visualize now:
```
library(tidyverse)

prop1 <- legislatives2017::premier_tour %>%
  group_by(Nuances) %>%
  summarise(prop_w = mean(civilite == "Mme"))

prop2 <- filter(legislatives2017::premier_tour, resultat != "elimine") %>%
  group_by(Nuances) %>%
  summarise(prop_w2 = mean(civilite == "Mme"))

full_join(prop1, prop2, "Nuances") %>%
  arrange(prop_w / prop_w2)
```

**Comment by ColinFay** [comment]
We can also get a visual assessment of parity with: 

`legislatives2017::premier_tour %>% 
   ggplot(aes(Nuances, fill = civilite)) + 
   geom_bar(position = "fill") +
   geom_hline(yintercept = 0.5) +
   theme_minimal()`

![rplot01](https://user-images.githubusercontent.com/17936236/27121249-c82340b8-50e6-11e7-91b7-d0cf76509788.png)

Colin
