### ISSUE TITLE
Circonscriptions des français de l'étranger sont absentes

### ISSUE THREAD

**Issue by jucor** [ThinkRstat/legislatives2017#3]
Les circonscriptions des français de l'étranger sont absentes de cette super visualisation. Comme pointé par @romainfrancois , la source https://www.data.gouv.fr/fr/datasets/carte-des-circonscriptions-legislatives-2012-et-2017/ ne les fournit hélas pas.

**Comment by jucor** [comment]
Issue [opened upstream](https://www.data.gouv.fr/fr/datasets/carte-des-circonscriptions-legislatives-2012-et-2017/#discussion-59468abb88ee381b400575d4).

**Comment by romainfrancois** [comment]
deja je pourrais récupérer l'info du nom des départements quand je scrape les données du ministère, ça me permettrait au moins d'avoir les infos dans les tableaux à droite.

**Comment by TomBor** [comment]
J'ai répondu à ce point sur [data.gouv](https://www.data.gouv.fr/fr/datasets/carte-des-circonscriptions-legislatives-2012-et-2017/#discussion-59468abb88ee381b400575d4-5). En soi c'est bien une absence, mais du point de vue de l'usage qui pourrait en être fait, simplifier par des symboles, en dehors de toute géographie, ces circonscriptions à plus de sens.
De la même manière rapproché les DOM-COM de la France métropolitaine permet une image plus synthétique.
